apiVersion: v1
kind: Pod
metadata:
  name: room-graph-receiver
spec:
  containers:
    - name: room-graph-receiver
      image: n0mimono/room-graph-receiver:latest
      imagePullPolicy: IfNotPresent
      command:
        - "pipenv"
        - "run"
        - "python"
        - "main.py"
      env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/secrets/credentials.json
      resources:
        limits:
          cpu: "200m"
          memory: "128Mi"
      volumeMounts:
        - name: secretdir
          mountPath: /etc/secrets
  volumes:
    - name: secretdir
      secret:
        secretName: credentials
        items:
          - key: credentials.json
            path: credentials.json
